### ISSUE TITLE
Support search and/or advanced search

### ISSUE THREAD

**Issue by larsgw** [cdli-gh/framework-api-client#3]

**Comment by abhijain2003** [comment]
can you provide more context

**Comment by larsgw** [comment]
The idea is to provide a method in the JS API and in the CLI to allow for interaction with the new CDLI search (https://cdli.mpiwg-berlin.mpg.de/docs/search).

**Comment by abhijain2003** [comment]
so what method basically we can add, 

like in search there are 3 methods
[Simple search](https://cdli.mpiwg-berlin.mpg.de/docs/search#content-simple-search)
[Advanced search](https://cdli.mpiwg-berlin.mpg.de/docs/search#content-advanced-search)
[Transliteration search](https://cdli.mpiwg-berlin.mpg.de/docs/search#content-transliteration-search)
